name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.20'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy && go mod download

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run tests
        run: |
          start_time=$(date +%s)
          gotestsum --format testdox -- -coverprofile=coverage.txt
          end_time=$(date +%s)
          echo "end_time=$end_time" >> $GITHUB_ENV
          echo "build_duration=$((end_time - start_time))"
          echo "build_duration=$((end_time - start_time))" >> $GITHUB_ENV

      - name: View coverage summary
        run: go tool cover -func=coverage.txt

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage.txt
          flags: unittests
          name: codecov-coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
